# This is a basic workflow to help you get started with Actions

name: Example CI/CD Github Action

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'force-app/main/default/**'
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Setup Node Environment
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Checkout Local Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Checkout rad-sfdx-cli-action
        uses: actions/checkout@v2
        with:
          repository: tahirihta/rad-sfdx-cli-action
          token: ${{ secrets.DEVOPS_TOKEN }}
          ref: main
          path: .github/actions/rad-sfdx-cli-action
      - name: Checkout rad-ci-action
        uses: actions/checkout@v2
        with:
          repository: tahirihta/rad-ci-action
          token: ${{ secrets.DEVOPS_TOKEN }}
          ref: main
          path: .github/actions/rad-ci-action
      - name: Install SFDX & Authorize Org
        uses: ./.github/actions/rad-sfdx-cli-action
        with:
          sfdx-auth-url: ${{ secrets.AUTH_SECRET }}
      - name: Validate Changes
        uses: ./.github/actions/rad-ci-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
